[2024-09-15T14:14:24.167+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-09-15T14:14:24.192+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: user_automate.streaming_data_from_user_random_api manual__2024-09-15T14:14:09.238241+00:00 [queued]>
[2024-09-15T14:14:24.205+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: user_automate.streaming_data_from_user_random_api manual__2024-09-15T14:14:09.238241+00:00 [queued]>
[2024-09-15T14:14:24.207+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 2
[2024-09-15T14:14:24.229+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): streaming_data_from_user_random_api> on 2024-09-15 14:14:09.238241+00:00
[2024-09-15T14:14:24.238+0000] {standard_task_runner.py:72} INFO - Started process 24 to run task
[2024-09-15T14:14:24.251+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'user_automate', 'streaming_data_from_user_random_api', 'manual__2024-09-15T14:14:09.238241+00:00', '--job-id', '15', '--raw', '--subdir', 'DAGS_FOLDER/kafka_streaming.py', '--cfg-path', '/tmp/tmph1ftml67']
[2024-09-15T14:14:24.277+0000] {standard_task_runner.py:105} INFO - Job 15: Subtask streaming_data_from_user_random_api
[2024-09-15T14:14:24.535+0000] {task_command.py:467} INFO - Running <TaskInstance: user_automate.streaming_data_from_user_random_api manual__2024-09-15T14:14:09.238241+00:00 [running]> on host e79900a31a80
[2024-09-15T14:14:25.515+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='user_automate' AIRFLOW_CTX_TASK_ID='streaming_data_from_user_random_api' AIRFLOW_CTX_EXECUTION_DATE='2024-09-15T14:14:09.238241+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-09-15T14:14:09.238241+00:00'
[2024-09-15T14:14:25.519+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-09-15T14:14:25.631+0000] {stream_data.py:9} INFO - started data streaming into kafka
[2024-09-15T14:14:26.538+0000] {conn.py:1527} WARNING - DNS lookup failed for borker:29092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2024-09-15T14:14:26.541+0000] {conn.py:315} ERROR - DNS lookup failed for borker:29092 (0)
[2024-09-15T14:14:26.542+0000] {conn.py:1205} INFO - Probing node bootstrap-0 broker version
[2024-09-15T14:14:27.388+0000] {conn.py:1527} WARNING - DNS lookup failed for borker:29092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2024-09-15T14:14:27.390+0000] {conn.py:315} ERROR - DNS lookup failed for borker:29092 (0)
[2024-09-15T14:14:28.221+0000] {conn.py:1527} WARNING - DNS lookup failed for borker:29092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2024-09-15T14:14:28.224+0000] {conn.py:315} ERROR - DNS lookup failed for borker:29092 (0)
[2024-09-15T14:14:28.225+0000] {conn.py:1205} INFO - Probing node bootstrap-0 broker version
[2024-09-15T14:14:29.074+0000] {conn.py:1527} WARNING - DNS lookup failed for borker:29092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2024-09-15T14:14:29.075+0000] {conn.py:315} ERROR - DNS lookup failed for borker:29092 (0)
[2024-09-15T14:14:29.077+0000] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/opt/airflow/dags/tasks/stream_data.py", line 11, in streaming_data
    producer = KafkaProducer(bootstrap_servers='borker:29092', max_block_ms=5000)
  File "/home/airflow/.local/lib/python3.9/site-packages/kafka/producer/kafka.py", line 381, in __init__
    client = KafkaClient(metrics=self._metrics, metric_group_prefix='producer',
  File "/home/airflow/.local/lib/python3.9/site-packages/kafka/client_async.py", line 244, in __init__
    self.config['api_version'] = self.check_version(timeout=check_timeout)
  File "/home/airflow/.local/lib/python3.9/site-packages/kafka/client_async.py", line 927, in check_version
    raise Errors.NoBrokersAvailable()
kafka.errors.NoBrokersAvailable: NoBrokersAvailable
[2024-09-15T14:14:29.151+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=user_automate, task_id=streaming_data_from_user_random_api, run_id=manual__2024-09-15T14:14:09.238241+00:00, execution_date=20240915T141409, start_date=20240915T141424, end_date=20240915T141429
[2024-09-15T14:14:29.191+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-09-15T14:14:29.193+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 15 for task streaming_data_from_user_random_api (NoBrokersAvailable; 24)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/opt/airflow/dags/tasks/stream_data.py", line 11, in streaming_data
    producer = KafkaProducer(bootstrap_servers='borker:29092', max_block_ms=5000)
  File "/home/airflow/.local/lib/python3.9/site-packages/kafka/producer/kafka.py", line 381, in __init__
    client = KafkaClient(metrics=self._metrics, metric_group_prefix='producer',
  File "/home/airflow/.local/lib/python3.9/site-packages/kafka/client_async.py", line 244, in __init__
    self.config['api_version'] = self.check_version(timeout=check_timeout)
  File "/home/airflow/.local/lib/python3.9/site-packages/kafka/client_async.py", line 927, in check_version
    raise Errors.NoBrokersAvailable()
kafka.errors.NoBrokersAvailable: NoBrokersAvailable
[2024-09-15T14:14:29.246+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-09-15T14:14:29.273+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-09-15T14:14:29.274+0000] {standard_task_runner.py:217} INFO - Process not found (most likely exited), stop collecting metrics
[2024-09-15T14:14:29.280+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
